---
- name: Remove htppd
  hosts: epam
  become: yes
  remote_user: ansible

  tasks:
  - name: Change grub-line
    lineinfile:
      state: present
      dest: /etc/default/grub
      backup: yes
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*  )\"[^\"]+)(\".*)'
      line: '\1 {{ item  }}\2'
    loop:
      - 'net.ifnames=0'
      - 'biosdevname=0'  

  - name: Update Grub 
    shell: grub2-mkconfig -o /boot/grub2/grub.cfg 
