---
# tasks file for deploy_apache

- name: Install Apache for Centos 8 
  yum: name=httpd state=latest

- name: Up Apache for Centos 8 
  service: name=httpd state=started enabled=yes  

- name : Check UP Apache
  shell: service httpd status | grep -i active 
  register: stdout_lines
- debug: var=stdout_lines

- name: Create index.html and added welcome with j2 
  template: src=index.j2 dest={{ dest_folder }}/index.html mode=0644

- name: Open 80 and 443 ports
  firewalld: 
    zone: public 
    port: "{{ item }}/tcp"
    permanent: yes 
    state: enabled
  loop: 
    - '80' 
    - '443'
  notify: 
    - open ports
