---
- name: Create new users  Lesson_02
  hosts: epam
  become: yes
  remote_user: ansible
  gather_facts: no 
  
  vars_files:
    - secret.yml  


  tasks: 
  - name: Create group
    group: 
      name: epam_users
      state: present


  - name: Add new user 
    ansible.builtin.user:
      name: "{{ item  }}"
      state: present
      create_home: yes
      comment: "{{ item }}@example.com"
      group: epam_users
      shell: /bin/bash 
      password: "{{ user_pass | password_hash('sha512','A512') }}"
      update_password: on_create

    loop: 
      - alice
      - bob 
      - carol

#  - name: Remove added users
#    ansible.builtin.user:
#      name: "{{ item }}"
#      state: absent
#      remove: yes 
#    loop:
#      - Alice
#      - Bob
#      - Carol
